/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Question_2;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 * ST10482636
 * @author lab_services_student
 */
public class Product_Sales_Application extends javax.swing.JFrame
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Product_Sales_Application.class.getName());
    
    // Data that was given to us
    private final int[][] productSales = {
        {300, 150, 700}, // Sales for year 1
        {250, 200, 600}  // Sales for year 2
    };
        
    // There is a sales limit of 500 as a Max
    private final int SALES_LIMIT = 500;
    
    // The salesLogic will be used to convert Total, Ave, Max and Min amount of sales
    private final Products_Sales salesLogic = new Products_Sales(productSales, SALES_LIMIT);


    public Product_Sales_Application() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Load_Product_Data_Button = new javax.swing.JButton();
        Save_Product_Data_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text_Area = new javax.swing.JTextArea();
        Years_Processed_Label = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_File = new javax.swing.JMenu();
        Menu_File_Exit = new javax.swing.JMenuItem();
        Menu_Edit = new javax.swing.JMenu();
        Menu_Edit_Load_Product_Data = new javax.swing.JMenuItem();
        Menu_Edit_Save_Product_Data = new javax.swing.JMenuItem();
        Menu_Edit_Clear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Load_Product_Data_Button.setText("Load Product Data");
        Load_Product_Data_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Load_Product_Data_ButtonActionPerformed(evt);
            }
        });

        Save_Product_Data_Button.setText("Save Product Data");
        Save_Product_Data_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_Product_Data_ButtonActionPerformed(evt);
            }
        });

        Text_Area.setColumns(20);
        Text_Area.setRows(5);
        jScrollPane1.setViewportView(Text_Area);

        Years_Processed_Label.setText("");

        Menu_File.setText("File");

        Menu_File_Exit.setText("Exit");
        Menu_File_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_File_ExitActionPerformed(evt);
            }
        });
        Menu_File.add(Menu_File_Exit);

        jMenuBar1.add(Menu_File);

        Menu_Edit.setText("Edit");

        Menu_Edit_Load_Product_Data.setText("Load Product Data");
        Menu_Edit.add(Menu_Edit_Load_Product_Data);

        Menu_Edit_Save_Product_Data.setText("Save Product Data");
        Menu_Edit.add(Menu_Edit_Save_Product_Data);

        Menu_Edit_Clear.setText("Clear");
        Menu_Edit_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Edit_ClearActionPerformed(evt);
            }
        });
        Menu_Edit.add(Menu_Edit_Clear);

        jMenuBar1.add(Menu_Edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Years_Processed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(Save_Product_Data_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Load_Product_Data_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Load_Product_Data_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Save_Product_Data_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Years_Processed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Load_Product_Data_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Load_Product_Data_ButtonActionPerformed
        
        int totalSales = salesLogic.GetTotalSales();
        double avgSales = salesLogic.GetAverageSales(); 
        int salesOver = salesLogic.GetSalesOverLimit();
        int salesUnder = salesLogic.GetSalesUnderLimit();
        var yearsProcessed = productSales.length; 


        String output;
        output = (
                   "Total Sales: " + totalSales + 
                    // Had to use the Math.round to make the Average Sales 1 Value
                   "\nAverage Sales: " + Math.round(avgSales) +
                   "\nSales over limit: " + salesOver +
                   "\nSales under limit: " + salesUnder  
                );

        Text_Area.setText(output);

        Years_Processed_Label.setText("Years Processed: " + yearsProcessed);
        
    }//GEN-LAST:event_Load_Product_Data_ButtonActionPerformed

    private void Save_Product_Data_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_Product_Data_ButtonActionPerformed
        // The data that needs to be saved is from the Text_Area
        String dataToSave = Text_Area.getText();

        String filename = "data.txt";
        
        // Imported the FileWriter for editing the data.txt file
        try (PrintWriter out = new PrintWriter(new FileWriter(filename))) 
        {
            out.println("DATA LOG");
            out.println("**********************");
            out.println(dataToSave);
            out.println("**********************");
        } 
        
        // Catch block
        catch (IOException ex) 
        {
            System.getLogger(Product_Sales_Application.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_Save_Product_Data_ButtonActionPerformed

    private void Menu_File_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_File_ExitActionPerformed
        // Exit
        System.exit(0);
    }//GEN-LAST:event_Menu_File_ExitActionPerformed

    private void Menu_Edit_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Edit_ClearActionPerformed
        // Clear
        Text_Area.setText("");
        Years_Processed_Label.setText("");
    }//GEN-LAST:event_Menu_Edit_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Product_Sales_Application().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load_Product_Data_Button;
    private javax.swing.JMenu Menu_Edit;
    private javax.swing.JMenuItem Menu_Edit_Clear;
    private javax.swing.JMenuItem Menu_Edit_Load_Product_Data;
    private javax.swing.JMenuItem Menu_Edit_Save_Product_Data;
    private javax.swing.JMenu Menu_File;
    private javax.swing.JMenuItem Menu_File_Exit;
    private javax.swing.JButton Save_Product_Data_Button;
    private javax.swing.JTextArea Text_Area;
    private java.awt.Label Years_Processed_Label;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
